/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cX9UUZ2QNgP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { JSX, SVGProps } from "react"

export function Footer() {
  return (
    <footer className="bg-muted py-12 animate-fade-in">
      <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-8 text-sm">
        <div className="grid gap-1">
          <h3 className="font-semibold">Music Platforms</h3>
          <Link href="https://open.spotify.com/artist/1ZdiGynuU5RZDk1qA2Ukqh" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <AirplayIcon className="h-5 w-5" />
            Spotify
          </Link>
          <Link href="https://music.apple.com/in/artist/krishna-chaturvedi/1678006853" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <AppleIcon className="h-5 w-5" />
            Apple Music
          </Link>
          <Link href="https://www.youtube.com/@KrishnaChaturvedi.Official" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <YoutubeIcon className="h-5 w-5" />
            YouTube 
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Indian Music</h3>
          <Link href="https://www.jiosaavn.com/artist/krishna-chaturvedi-songs/2d0KsMo-sEU_" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <FileMusicIcon className="h-5 w-5" />
            JioSaavn
          </Link>
          <Link href="https://gaana.com/artist/krishna-chaturvedi" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <FileMusicIcon className="h-5 w-5" />
            Gaana
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Social Media</h3>
          <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <InstagramIcon className="h-5 w-5" />
            Instagram
          </Link>
          <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <TwitterIcon className="h-5 w-5" />
            Twitter
          </Link>
          <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
            <FacebookIcon className="h-5 w-5" />
            Facebook
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Legal</h3>
          <Link href="#" className="hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Cookie Policy
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">Contact</h3>
          <Link href="#" className="hover:underline" prefetch={false}>
            Support
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Booking
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Management
          </Link>
        </div>
        <div className="grid gap-1">
          <h3 className="font-semibold">About</h3>
          <Link href="#" className="hover:underline" prefetch={false}>
            Biography
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Discography
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Tour Dates
          </Link>
        </div>
      </div>
    </footer>
  )
}

function AirplayIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1" />
      <path d="m12 15 5 6H7Z" />
    </svg>
  )
}


function AppleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function FacebookIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function FileMusicIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="14" cy="16" r="2" />
      <circle cx="6" cy="18" r="2" />
      <path d="M4 12.4V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-7.5" />
      <path d="M8 18v-7.7L16 9v7" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function YoutubeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
