/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WPxRuNn7vjw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Video_section() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container space-y-8 px-4 md:px-6">
        <div className="space-y-4 text-center md:max-w-2xl md:mx-auto">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Immersive Video Experience</h2>
          <p className="text-muted-foreground md:text-xl">
            Lose yourself in our captivating video loop, where time stands still and the world around you fades away.
          </p>
        </div>
        <div className="relative aspect-video overflow-hidden rounded-lg">
          <video className="w-full h-full object-cover" autoPlay loop muted playsInline>
            <source
              src="../../show_video.mp4"
              type="video/mp4"
            />
          </video>
         
        </div>
      </div>
    </section>
  )
}
