


/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pXeS6jlFkrL
*
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Youtube_video() {
  return (
    <section className="w-full py-12 md:py-24">
      <div className="container grid gap-8 px-4 md:px-6">
        <div className="grid gap-2">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">Most Recent Videos</h2>
          <p className="text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Check out the latest videos from our talented artists.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
          <div className="relative group overflow-hidden rounded-lg shadow-lg">
            <Link href="https://www.youtube.com/watch?v=CUfhpNxNV9c" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View video</span>
            </Link>
            <img
              src="../../project_1.jpg"
              alt="Video thumbnail"
              width={1280}
              height={720}
              className="object-cover w-full aspect-video group-hover:opacity-50 transition-opacity"
            />
            <div className="p-4 bg-background">
              <h3 className="text-lg font-semibold line-clamp-2">Door Na Hona Shambhu </h3>
              <div className="grid gap-1 text-sm text-muted-foreground">
                <div>Singer - Krishna Chaturvedi</div>
                <div>Composer - Pankaj VRK</div>
                <div>Lyrics - Gourav Pawar Bhawsar</div>
              </div>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg shadow-lg">
            <Link href="https://www.youtube.com/watch?v=WAOokmrVq3k" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View video</span>
            </Link>
            <img
              src="../../project_2.jpg"
              alt="Video thumbnail"
              width={1280}
              height={720}
              className="object-cover w-full aspect-video group-hover:opacity-50 transition-opacity"
            />
            <div className="p-4 bg-background">
              <h3 className="text-lg font-semibold line-clamp-2">Mere Bholenath Ji </h3>
              <div className="grid gap-1 text-sm text-muted-foreground">
                <div>Singer - Krishna Chaturvedi</div>
                <div>Music - Rajat Randhawa</div>
                <div>Lyrics -  Naveen Agrawal</div>
              </div>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg shadow-lg">
            <Link href="https://www.youtube.com/watch?v=HeOiosVizYo" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">View video</span>
            </Link>
            <img
              src="../../project_3.jpg"
              alt="Video thumbnail"
              width={1280}
              height={720}
              className="object-cover w-full aspect-video group-hover:opacity-50 transition-opacity"
            />
            <div className="p-4 bg-background">
              <h3 className="text-lg font-semibold line-clamp-2">Sun Bholeshankar </h3>
              <div className="grid gap-1 text-sm text-muted-foreground">
                <div>Singer - Krishna Chaturvedi</div>
                <div>Composer - Pankaj VRK</div>
                <div>Music -  Tarun Rishi</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
